---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:12 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - ebe9cbe8-d78a-4f4f-76f4-385eca67b8a6
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 04441700-2dd3-4b6e-7106-48ac92c2bcce::c4953dba-849e-4a1d-a301-78882488c122
    body:
      encoding: US-ASCII
      string: ! '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:11 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 25 Mar 2015 16:25:11 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 3e679a5a-298e-4d6f-528b-de93ca4307e4, a22ff8be-67da-4fcc-6143-e9da71566902
      X-Frame-Options:
      - DENY
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"5553cebd-5da9-4425-9d50-b4ee0be5a0f2"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:12 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Apaasal-test-app-min-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:12 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - c6cb226a-83af-449b-572e-8cad3875112a
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 5585b0e5-bad7-4c3c-46b2-280e29ce82e6::0c153555-a482-4856-82fa-e22d8ad10e3c
    body:
      encoding: US-ASCII
      string: ! "{\n  \"total_results\": 0,\n  \"total_pages\": 1,\n  \"prev_url\":
        null,\n  \"next_url\": null,\n  \"resources\": [\n\n  ]\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:12 GMT
recorded_with: VCR 2.9.3
