---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:16 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - b38ba9bb-4dc6-4a32-4683-3be98d8dcfad
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - dc3c5fb9-1a62-469f-7777-82ed8bfb9fd0::d3d871ec-c33b-481b-b7f4-1131caf42b0d
    body:
      encoding: US-ASCII
      string: ! '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:16 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 25 Mar 2015 16:25:16 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 38bdaab0-f421-4ad0-5d03-c939bd941f43, f0532e77-4e8b-407d-7bc6-02b5a2225da9
      X-Frame-Options:
      - DENY
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"7913d21d-71f9-4c55-aef3-c711204e21be"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:16 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Apaasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:16 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - c7b5c3ad-68f1-4345-6863-4229834c194b
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 4116ea23-cf82-4255-4fb9-5421b8b78ee9::2accd66f-7d20-4a44-b7d5-2dbeeadd33fe
    body:
      encoding: US-ASCII
      string: ! "{\n  \"total_results\": 0,\n  \"total_pages\": 1,\n  \"prev_url\":
        null,\n  \"next_url\": null,\n  \"resources\": [\n\n  ]\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:16 GMT
recorded_with: VCR 2.9.3
