---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 08 Apr 2015 15:40:25 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 0440f793-0e8a-44f4-7f56-2be3fc65ef60
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 6471a3f9-bd06-4f68-79b2-88d4687dc322::eb7b3da6-b714-43e8-aa38-95444d34a1a8
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 15:40:25 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 08 Apr 2015 15:40:25 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 39402128-8f5f-4bad-4de0-1ff517c9fe9b, ac5ad4aa-489c-4661-7414-75bc877ac1ff
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"dfb0d1f6-3733-4810-a9a2-ed55d7da3eb5"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 15:40:25 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 08 Apr 2015 15:40:25 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 6ecdbdce-0e28-42cc-4c30-e791fed754e1
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 32b33742-689c-4076-5eaa-10a340fd89d0::42f7f9d1-f608-4ed4-8f67-dede0dcc9d1e
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Wed, 08 Apr 2015 15:40:25 GMT
recorded_with: VCR 2.9.3
