---
http_interactions:
- request:
    method: post
    uri: https://api.cloudcontrol.com/token
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - bytes
      Access-Control-Allow-Headers:
      - X-Requested-With, Authorization, Content-Type, Content-Length, Accept
      Access-Control-Allow-Methods:
      - POST, GET, PUT, DELETE
      Access-Control-Allow-Origin:
      - "*"
      Age:
      - '0'
      Allow:
      - POST, OPTIONS
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 18:01:52 GMT
      Server:
      - gunicorn/19.2.1
      Strict-Transport-Security:
      - max-age=15768000
      Vary:
      - Accept
      Via:
      - 1.1 varnish
      x-host:
      - api.cloudcontrol.com
      x-url:
      - "/token"
      X-Varnish:
      - '2470564168'
      X-varnish-cache:
      - MISS
      Content-Length:
      - '84'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"token": "__TOKEN__", "expires": "2015-04-08T18:16:52.200103"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 18:01:52 GMT
- request:
    method: put
    uri: https://api.cloudcontrol.com/app/paasaltestappminproperties13/deployment/paasal
    body:
      encoding: UTF-8
      string: '{"min_boxes":1}'
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - bytes
      Access-Control-Allow-Headers:
      - X-Requested-With, Authorization, Content-Type, Content-Length, Accept
      Access-Control-Allow-Methods:
      - POST, GET, PUT, DELETE
      Access-Control-Allow-Origin:
      - "*"
      Age:
      - '0'
      Allow:
      - GET, POST, PUT, DELETE, HEAD, OPTIONS
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 18:01:53 GMT
      Server:
      - gunicorn/19.2.1
      Strict-Transport-Security:
      - max-age=15768000
      Vary:
      - Accept, Cookie, Accept-Encoding
      Via:
      - 1.1 varnish
      x-host:
      - api.cloudcontrol.com
      x-url:
      - "/app/paasaltestappminproperties13/deployment/paasal"
      X-Varnish:
      - '890444435'
      X-varnish-cache:
      - MISS
      Content-Length:
      - '368'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"name": "paasaltestappminproperties13/paasal", "stack": {"name": "pinky"},
        "dep_id": "deph9tffrvp", "branch": "ssh://paasaltestappminproperties13@cloudcontrolled.com/repository.git",
        "users": [], "static_files": "(removed)", "billing_account": null, "version":
        "2fecc963d0e7a31b1cdd1f06901f1efe644026c2", "state": "deploying", "date_created":
        "2015-04-08T17:54:23", "date_modified": "2015-04-08T18:01:53.728465", "is_default":
        false, "default_subdomain": "paasal-paasaltestappminproperties13.cloudcontrolled.com",
        "min_boxes": 1, "max_boxes": 1, "billed_boxes": {"boxes": 0.0, "free_boxes":
        0.0, "until": 1428516113, "costs": 0.0}, "billed_addons": []}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 18:01:54 GMT
- request:
    method: get
    uri: https://api.cloudcontrol.com/app/paasaltestappminproperties13
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - bytes
      Access-Control-Allow-Headers:
      - X-Requested-With, Authorization, Content-Type, Content-Length, Accept
      Access-Control-Allow-Methods:
      - POST, GET, PUT, DELETE
      Access-Control-Allow-Origin:
      - "*"
      Age:
      - '0'
      Allow:
      - GET, POST, DELETE, HEAD, OPTIONS
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 18:01:54 GMT
      Server:
      - gunicorn/19.2.1
      Strict-Transport-Security:
      - max-age=15768000
      Vary:
      - Accept, Cookie, Accept-Encoding
      Via:
      - 1.1 varnish
      x-host:
      - api.cloudcontrol.com
      x-url:
      - "/app/paasaltestappminproperties13"
      X-Varnish:
      - '2470564370'
      X-varnish-cache:
      - MISS
      Content-Length:
      - '313'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"name": "paasaltestappminproperties13", "buildpack_url": null, "repository":
        "ssh://paasaltestappminproperties13@cloudcontrolled.com/repository.git", "type":
        {"name": "nodejs"}, "owner": {"username": "__cloudcontrol:username__", "first_name":
        "", "last_name": "", "email": "__cloudcontrol:user__", "is_active": true,
        "billing_without_payment_info": false}, "users": [{"username": "__cloudcontrol:username__",
        "email": "__cloudcontrol:user__", "role": ""}], "invitations": [], "date_created":
        "2015-04-08T17:54:22", "date_modified": "2015-04-08T17:54:22", "deployments":
        [{"name": "paasaltestappminproperties13/paasal", "dep_id": "deph9tffrvp"}]}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 18:01:54 GMT
recorded_with: VCR 2.9.3
