AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - nucleus.gemspec

Style/MutableConstant:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
