AllCops:
  Exclude:
    - bin/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

inherit_from: .rubocop_todo.yml
