AllCops:
  Exclude:
    - bin/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

inherit_from: .rubocop_todo.yml
