language: ruby
cache: bundler
# use docker based environment
sudo: false

rvm:
  - 2.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

gemfile:
  - Gemfile
  
addons:
  code_climate:
    repo_token: 3a3d0c72cae4846855221615e1d8690c0dd08336ef8904b8a8d109e51037ee2b
