---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:35:53 GMT
      Request-Id:
      - d3d5c135-a1e8-4d4e-87ed-660cb40b6e8a
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.118189202'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/04/02 05:56:32 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:35:54 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:35:54 GMT
      ETag:
      - '"12095c88d5a258749ba3b5f776e2bc42"'
      Last-Modified:
      - Thu, 02 Apr 2015 13:35:25 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2345'
      Request-Id:
      - 94ff9718-9b90-4584-b7cb-ceff33cb4144
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.087629394'
      Content-Length:
      - '391'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-02T13:34:48Z","id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-02T13:34:49Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-02T13:35:25Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:35:54 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:35:55 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2344'
      Request-Id:
      - ab85fa6f-7753-488c-8adf-88cfc8a0dff6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.111821821'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:35:55 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:35:56 GMT
      ETag:
      - '"12095c88d5a258749ba3b5f776e2bc42"'
      Last-Modified:
      - Thu, 02 Apr 2015 13:35:25 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2343'
      Request-Id:
      - c955f9bd-8085-49c4-82f6-70c58ec3917c
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.02610532'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:35:56 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:35:56 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2342'
      Request-Id:
      - 025d67eb-0b2a-4b93-b965-b0b8e38a5a7f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.045457304'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:35:56 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..2
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:35:57 GMT
      ETag:
      - '"5eb4aaa8dbc07ba312b4759bd4e70931"'
      Last-Modified:
      - Thu, 02 Apr 2015 06:34:49 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2341'
      Request-Id:
      - 71f30047-d0b3-4edf-8863-209cca77540b
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.028987991'
      Content-Length:
      - '321'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:34:48Z","description":"Initial
        release","id":"d981418d-47e5-4d09-a5ce-60a6b38edde7","slug":null,"updated_at":"2015-04-02T13:34:48Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:34:49Z","description":"Enable
        Logplex","id":"fbd21090-454e-4317-92a4-6b49bafcf6cc","slug":null,"updated_at":"2015-04-02T13:34:49Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2}]'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:35:57 GMT
recorded_with: VCR 2.9.3
