---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:47 GMT
      Request-Id:
      - 80cbf28d-1ef9-4469-a094-c623dbfd5756
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.127662633'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/04/06 13:31:08 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:48 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:47 GMT
      ETag:
      - '"307df08c863c7e528d3aee8f25ece96a"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:35:20 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2160'
      Request-Id:
      - 4da81e75-36c6-46dd-a3ea-4e48e5da8c0a
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.126924386'
      Content-Length:
      - '393'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-06T20:34:46Z","id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-06T20:34:47Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-06T20:35:20Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:49 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:48 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2159'
      Request-Id:
      - 5ae7852c-7a92-4164-848e-68f8c9a4f557
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.106975643'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:49 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:49 GMT
      ETag:
      - '"307df08c863c7e528d3aee8f25ece96a"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:35:20 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2158'
      Request-Id:
      - 8ef01d43-ef31-4604-9fde-4dc3ce383851
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.029694342'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:50 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:49 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2157'
      Request-Id:
      - 74e8a30e-28b3-4a26-9ae6-840ec6786ce9
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.041031404'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:51 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..2
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:50 GMT
      ETag:
      - '"5eb4aaa8dbc07ba312b4759bd4e70931"'
      Last-Modified:
      - Mon, 06 Apr 2015 13:34:47 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2156'
      Request-Id:
      - 231d0be7-8cdf-4632-a488-b9a339209734
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.035000671'
      Content-Length:
      - '321'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:34:46Z","description":"Initial
        release","id":"d07fe512-f94b-46e8-948e-bec155745725","slug":null,"updated_at":"2015-04-06T20:34:46Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:34:47Z","description":"Enable
        Logplex","id":"dff6c310-5c2f-45b2-856c-ffef987ae966","slug":null,"updated_at":"2015-04-06T20:34:47Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:51 GMT
recorded_with: VCR 2.9.3
