---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:59:01 GMT
      Request-Id:
      - f340e48b-79cd-46d0-b609-39d09adedd75
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.146423164'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/25 09:59:00 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:59:01 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:59:02 GMT
      RateLimit-Remaining:
      - '2166'
      Request-Id:
      - 9cfb7266-4ba5-4101-ae09-25a6dee42a12
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 404 Not Found
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.019948745'
      Content-Length:
      - '92'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"resource":"app","id":"not_found","message":"Couldn''t find that
        app."}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:59:02 GMT
recorded_with: VCR 2.9.3
