---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:22:31 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 0a86515d-11fc-46ee-708f-0ae43af8b33c
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 8c87121b-bce7-4e1c-5a60-e7f5c4af3e3d::575b1e9f-6250-4ccb-b255-8f2bd0157ca1
    body:
      encoding: US-ASCII
      string: ! '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:22:31 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 25 Mar 2015 16:22:31 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 2aa2e558-7f5a-49fe-667f-243016654d0f, 7bc37f9c-7ec4-4ba3-7ce1-d761b32772e3
      X-Frame-Options:
      - DENY
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"77aaadb2-eeef-4a6b-a45c-f6984f781515"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:22:31 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:22:31 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 297806ee-2af2-4739-7931-9fb2d2b33e89
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - bab0085b-683e-427f-7c24-9e896ca8e9f5::ce94b63f-47e9-4da7-aa8e-12c1a4ff4660
    body:
      encoding: US-ASCII
      string: ! "{\n  \"total_results\": 0,\n  \"total_pages\": 1,\n  \"prev_url\":
        null,\n  \"next_url\": null,\n  \"resources\": [\n\n  ]\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:22:31 GMT
recorded_with: VCR 2.9.3
