---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:22:46 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 6b0e5a5a-4f2a-4758-76f0-67fabddb854f
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 29560634-8cdb-4174-547d-762b9ebba1a8::6f5f565e-bc17-409c-982f-0ee644401ede
    body:
      encoding: US-ASCII
      string: ! '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:22:46 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 25 Mar 2015 16:22:46 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - ecb08ad4-b609-4eef-6162-65cf878d5ad8, 1bb0ac17-edde-4642-692f-36ae9dad3b38
      X-Frame-Options:
      - DENY
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"bec21c8c-89e2-4339-a1be-9a5653a5e20a"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:22:46 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:22:47 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 4ec0f6cc-756c-4385-4e99-4a568036b296
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - e2ca3983-dd20-41a5-77ae-79c4ce72922e::dbb5f22a-a356-47d3-943d-0013bb4e7e2f
    body:
      encoding: US-ASCII
      string: ! "{\n  \"total_results\": 0,\n  \"total_pages\": 1,\n  \"prev_url\":
        null,\n  \"next_url\": null,\n  \"resources\": [\n\n  ]\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:22:46 GMT
recorded_with: VCR 2.9.3
