---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:02 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 752be49e-8188-4e52-5348-5f3feced6545
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 37d45657-d963-470f-7243-6f87d7faae75::262c5e16-9b4e-4d85-8b68-bcd71202c696
    body:
      encoding: US-ASCII
      string: ! '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:02 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 25 Mar 2015 16:25:02 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 0ee0c802-794b-4d20-65ac-f524be9c5b3f, 6582bc7b-b744-4dde-4e80-388b700c567f
      X-Frame-Options:
      - DENY
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"be7680b4-8093-431c-90a3-75c5bcf96555"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:02 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Apaasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '1775'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:02 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 9de4d3d3-b348-4607-4bfb-a7facde0a25e
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 80ccf4fd-3a3b-4f7c-4849-f55d61d1f5c9::efc0a17c-c27a-48f7-9f5e-06d83baf7e32
    body:
      encoding: US-ASCII
      string: ! "{\n  \"total_results\": 1,\n  \"total_pages\": 1,\n  \"prev_url\":
        null,\n  \"next_url\": null,\n  \"resources\": [\n    {\n      \"metadata\":
        {\n        \"guid\": \"eb5c7fd1-4985-4065-be56-f5d1cc398dad\",\n        \"url\":
        \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad\",\n        \"created_at\":
        \"2015-03-25T16:22:35+00:00\",\n        \"updated_at\": \"2015-03-25T16:25:02+00:00\"\n
        \     },\n      \"entity\": {\n        \"name\": \"paasal-test-app-all-updated\",\n
        \       \"production\": false,\n        \"space_guid\": \"d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n
        \       \"stack_guid\": \"b4d24013-b385-4db1-a171-b4e151a87c46\",\n        \"buildpack\":
        \"nodejs_buildpack\",\n        \"detected_buildpack\": null,\n        \"environment_json\":
        {\n          \"our_test_var_key\": \"our_updated_test_var_value\",\n          \"our_test_var_key2\":
        \"our_test_var_value2\"\n        },\n        \"memory\": 256,\n        \"instances\":
        2,\n        \"disk_quota\": 1024,\n        \"state\": \"STARTED\",\n        \"version\":
        \"48e73ea0-4a8f-4ed6-a9b4-6350e8bb9f40\",\n        \"command\": null,\n        \"console\":
        false,\n        \"debug\": null,\n        \"staging_task_id\": \"d7cdd1247c3046e19943196de87b8c86\",\n
        \       \"package_state\": \"PENDING\",\n        \"health_check_timeout\":
        null,\n        \"staging_failed_reason\": null,\n        \"docker_image\":
        null,\n        \"package_updated_at\": \"2015-03-25T16:23:07+00:00\",\n        \"detected_start_command\":
        \"node server.js\",\n        \"space_url\": \"/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n
        \       \"stack_url\": \"/v2/stacks/b4d24013-b385-4db1-a171-b4e151a87c46\",\n
        \       \"events_url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/events\",\n
        \       \"service_bindings_url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/service_bindings\",\n
        \       \"routes_url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/routes\"\n
        \     }\n    }\n  ]\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:02 GMT
- request:
    method: put
    uri: https://api.10.244.0.34.xip.io/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad
    body:
      encoding: UTF-8
      string: ! '{"instances":1}'
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Length:
      - '1508'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:02 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 204170b6-4601-43e8-57a2-a093a057ce8c
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - fc70dcfb-4127-4b24-505d-b5756c4a9d08::8b3ceb8c-562c-4ea3-82c0-d84307838850
    body:
      encoding: US-ASCII
      string: ! "{\n  \"metadata\": {\n    \"guid\": \"eb5c7fd1-4985-4065-be56-f5d1cc398dad\",\n
        \   \"url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad\",\n    \"created_at\":
        \"2015-03-25T16:22:35+00:00\",\n    \"updated_at\": \"2015-03-25T16:25:02+00:00\"\n
        \ },\n  \"entity\": {\n    \"name\": \"paasal-test-app-all-updated\",\n    \"production\":
        false,\n    \"space_guid\": \"d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n    \"stack_guid\":
        \"b4d24013-b385-4db1-a171-b4e151a87c46\",\n    \"buildpack\": \"nodejs_buildpack\",\n
        \   \"detected_buildpack\": null,\n    \"environment_json\": {\n      \"our_test_var_key\":
        \"our_updated_test_var_value\",\n      \"our_test_var_key2\": \"our_test_var_value2\"\n
        \   },\n    \"memory\": 256,\n    \"instances\": 1,\n    \"disk_quota\": 1024,\n
        \   \"state\": \"STARTED\",\n    \"version\": \"48e73ea0-4a8f-4ed6-a9b4-6350e8bb9f40\",\n
        \   \"command\": null,\n    \"console\": false,\n    \"debug\": null,\n    \"staging_task_id\":
        \"d7cdd1247c3046e19943196de87b8c86\",\n    \"package_state\": \"PENDING\",\n
        \   \"health_check_timeout\": null,\n    \"staging_failed_reason\": null,\n
        \   \"docker_image\": null,\n    \"package_updated_at\": \"2015-03-25T16:23:07+00:00\",\n
        \   \"detected_start_command\": \"node server.js\",\n    \"space_url\": \"/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n
        \   \"stack_url\": \"/v2/stacks/b4d24013-b385-4db1-a171-b4e151a87c46\",\n
        \   \"events_url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/events\",\n
        \   \"service_bindings_url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/service_bindings\",\n
        \   \"routes_url\": \"/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/routes\"\n
        \ }\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:02 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps/eb5c7fd1-4985-4065-be56-f5d1cc398dad/routes
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '2056'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:02 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - bfdf4d92-7030-42ee-4dbc-b6a717ee0d92
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - d17c83ae-788b-4c14-44c8-85c201086f7c::95a8db4c-b669-44af-8c74-79d13ee3dbf9
    body:
      encoding: US-ASCII
      string: ! "{\n  \"total_results\": 3,\n  \"total_pages\": 1,\n  \"prev_url\":
        null,\n  \"next_url\": null,\n  \"resources\": [\n    {\n      \"metadata\":
        {\n        \"guid\": \"df0374e4-94c8-4f00-aa0f-3a9d8126cc86\",\n        \"url\":
        \"/v2/routes/df0374e4-94c8-4f00-aa0f-3a9d8126cc86\",\n        \"created_at\":
        \"2015-03-25T16:22:35+00:00\",\n        \"updated_at\": null\n      },\n      \"entity\":
        {\n        \"host\": \"eb5c7fd1-4985-4065-be56-f5d1cc398dad\",\n        \"domain_guid\":
        \"0a7ac015-b059-47d3-b1a2-873a6e370f36\",\n        \"space_guid\": \"d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n
        \       \"domain_url\": \"/v2/domains/0a7ac015-b059-47d3-b1a2-873a6e370f36\",\n
        \       \"space_url\": \"/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n
        \       \"apps_url\": \"/v2/routes/df0374e4-94c8-4f00-aa0f-3a9d8126cc86/apps\"\n
        \     }\n    },\n    {\n      \"metadata\": {\n        \"guid\": \"45e03631-b162-44ed-b766-1d7e73d39f60\",\n
        \       \"url\": \"/v2/routes/45e03631-b162-44ed-b766-1d7e73d39f60\",\n        \"created_at\":
        \"2015-03-25T16:22:57+00:00\",\n        \"updated_at\": null\n      },\n      \"entity\":
        {\n        \"host\": \"cf-bosh-local\",\n        \"domain_guid\": \"a055ee95-7d64-4352-9e5e-7eea55ecf706\",\n
        \       \"space_guid\": \"d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n        \"domain_url\":
        \"/v2/domains/a055ee95-7d64-4352-9e5e-7eea55ecf706\",\n        \"space_url\":
        \"/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n        \"apps_url\":
        \"/v2/routes/45e03631-b162-44ed-b766-1d7e73d39f60/apps\"\n      }\n    },\n
        \   {\n      \"metadata\": {\n        \"guid\": \"c59165ff-57c1-4187-b8cf-2b00e7f36ec7\",\n
        \       \"url\": \"/v2/routes/c59165ff-57c1-4187-b8cf-2b00e7f36ec7\",\n        \"created_at\":
        \"2015-03-25T16:22:58+00:00\",\n        \"updated_at\": null\n      },\n      \"entity\":
        {\n        \"host\": \"\",\n        \"domain_guid\": \"a055ee95-7d64-4352-9e5e-7eea55ecf706\",\n
        \       \"space_guid\": \"d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n        \"domain_url\":
        \"/v2/domains/a055ee95-7d64-4352-9e5e-7eea55ecf706\",\n        \"space_url\":
        \"/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940\",\n        \"apps_url\":
        \"/v2/routes/c59165ff-57c1-4187-b8cf-2b00e7f36ec7/apps\"\n      }\n    }\n
        \ ]\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:02 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/domains/0a7ac015-b059-47d3-b1a2-873a6e370f36
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '283'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 25 Mar 2015 16:25:02 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - b2a883de-9d2f-4523-5121-9834641ab074
      X-Cf-Warnings:
      - Endpoint+deprecated
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 1e943337-86d2-4079-67f2-dc3f5645710a::c4af79bc-9da6-47ff-a817-42a61d7dc365
    body:
      encoding: US-ASCII
      string: ! "{\n  \"metadata\": {\n    \"guid\": \"0a7ac015-b059-47d3-b1a2-873a6e370f36\",\n
        \   \"url\": \"/v2/domains/0a7ac015-b059-47d3-b1a2-873a6e370f36\",\n    \"created_at\":
        \"2014-12-05T16:23:46+00:00\",\n    \"updated_at\": \"2015-03-19T07:07:29+00:00\"\n
        \ },\n  \"entity\": {\n    \"name\": \"10.244.0.34.xip.io\"\n  }\n}"
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:25:02 GMT
recorded_with: VCR 2.9.3
