---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:32:53 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 37183303-e8d8-44b9-7ec2-7d41a652ee03
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 2f00f606-8cd9-467c-45de-b5db1ac850fe::5c07fdc8-de9c-4876-99f9-54013ecac301
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:44 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Thu, 02 Apr 2015 12:32:52 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - e77e94d9-7d06-4c00-416a-a005bbb6e3b8, 1abece13-bd02-4dca-5ec9-9afcbcc18ba6
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"8b352c46-3823-439b-a61d-26fecf7c25bd"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:45 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:32:53 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 8a0259d4-1438-4626-6270-2fbdf3ceb0e1
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 4293c5a6-be72-4cdc-5763-b4891423b6c2::dee07267-fd0e-43b1-bf62-db36fdc50b1f
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:45 GMT
recorded_with: VCR 2.9.3
