---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:34:57 GMT
      Request-Id:
      - edd94ef2-284a-4d36-b783-6871d04d2e27
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.121848378'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/04/06 13:31:08 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:34:58 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-properties
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:34:58 GMT
      ETag:
      - '"9cbe85c7e10dd852a6365ae8e9c89a98"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:34:52 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2194'
      Request-Id:
      - 8b16393c-617b-413f-ad61-293d04aa6082
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.064460784'
      Content-Length:
      - '392'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-06T20:34:51Z","id":"787598df-fb3a-44aa-abb2-2326ecbbda1d","git_url":"git@heroku.com:paasal-test-app-min-properties.git","maintenance":false,"name":"paasal-test-app-min-properties","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-06T20:34:52Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-06T20:34:52Z","web_url":"https://paasal-test-app-min-properties.herokuapp.com/"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:34:59 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/787598df-fb3a-44aa-abb2-2326ecbbda1d/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:34:58 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2193'
      Request-Id:
      - 330e276b-c96d-4487-b9dc-f5a1bd42a914
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.1158498'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:00 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/787598df-fb3a-44aa-abb2-2326ecbbda1d/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:34:59 GMT
      ETag:
      - '"9cbe85c7e10dd852a6365ae8e9c89a98"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:34:52 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2192'
      Request-Id:
      - 6c332780-697a-4c31-8c25-9ccd4f74b05f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.045932621'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:00 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/787598df-fb3a-44aa-abb2-2326ecbbda1d/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:00 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2191'
      Request-Id:
      - 9a48cbf9-4028-488c-9027-9bd41ed31253
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.08919349'
      Content-Length:
      - '98'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-java"},"ordinal":0}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:01 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/787598df-fb3a-44aa-abb2-2326ecbbda1d/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..2
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:35:00 GMT
      ETag:
      - '"5eb4aaa8dbc07ba312b4759bd4e70931"'
      Last-Modified:
      - Mon, 06 Apr 2015 13:34:52 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2190'
      Request-Id:
      - b8745475-5cf3-42a3-b7bd-086945871b0e
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.031338116'
      Content-Length:
      - '325'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"787598df-fb3a-44aa-abb2-2326ecbbda1d","name":"paasal-test-app-min-properties"},"created_at":"2015-04-06T20:34:51Z","description":"Initial
        release","id":"3e9a5f76-373e-41b9-9299-9e9a4b9aaa54","slug":null,"updated_at":"2015-04-06T20:34:51Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"787598df-fb3a-44aa-abb2-2326ecbbda1d","name":"paasal-test-app-min-properties"},"created_at":"2015-04-06T20:34:52Z","description":"Enable
        Logplex","id":"c9e9b3df-8918-400f-8bd8-860616561d65","slug":null,"updated_at":"2015-04-06T20:34:52Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:35:02 GMT
recorded_with: VCR 2.9.3
