---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:21 GMT
      Request-Id:
      - fdc8473c-35b6-4938-8c9d-5c730af7b9a6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.117838736'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/19 09:27:04 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:21 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-properties
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:21 GMT
      ETag:
      - '"678b3806a73b64b8e88dbdab4bedf4f3"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:28:16 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2037'
      Request-Id:
      - 1fe21406-30b9-4c2b-b477-7f9be67b934f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.065428047'
      Content-Length:
      - '391'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-19T16:28:15Z","id":"b8f5a84b-6545-44c2-83cd-15daed2b9bc1","git_url":"git@heroku.com:paasal-test-app-min-properties.git","maintenance":false,"name":"paasal-test-app-min-properties","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-19T16:28:16Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-19T16:28:16Z","web_url":"https://paasal-test-app-min-properties.herokuapp.com/"}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:21 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/b8f5a84b-6545-44c2-83cd-15daed2b9bc1/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:22 GMT
      ETag:
      - '"678b3806a73b64b8e88dbdab4bedf4f3"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:28:16 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2036'
      Request-Id:
      - 2b6d39e1-7cc1-4e0d-b1a2-a0c90f12bfac
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.04646609'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:22 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/b8f5a84b-6545-44c2-83cd-15daed2b9bc1/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:22 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2035'
      Request-Id:
      - bd0b4b60-48c4-4912-a240-7cfd33aa7ebc
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.044690104'
      Content-Length:
      - '98'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-java"},"ordinal":0}]'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:22 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/b8f5a84b-6545-44c2-83cd-15daed2b9bc1/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:23 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2034'
      Request-Id:
      - 42a06743-85e9-49d9-8029-27e0c010d75f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.109400087'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:23 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/b8f5a84b-6545-44c2-83cd-15daed2b9bc1/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..2
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:24 GMT
      ETag:
      - '"5eb4aaa8dbc07ba312b4759bd4e70931"'
      Last-Modified:
      - Thu, 19 Mar 2015 09:28:15 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2033'
      Request-Id:
      - 471ddcf1-2149-4c43-bf30-c068f9552e89
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.057986119'
      Content-Length:
      - '314'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"b8f5a84b-6545-44c2-83cd-15daed2b9bc1","name":"paasal-test-app-min-properties"},"created_at":"2015-03-19T16:28:15Z","description":"Initial
        release","id":"388933c4-d4af-4f55-9cd3-940b2c7abaca","slug":null,"updated_at":"2015-03-19T16:28:15Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"b8f5a84b-6545-44c2-83cd-15daed2b9bc1","name":"paasal-test-app-min-properties"},"created_at":"2015-03-19T16:28:15Z","description":"Enable
        Logplex","id":"d83fd991-8055-4c3c-99fb-e395ee0f10ef","slug":null,"updated_at":"2015-03-19T16:28:15Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2}]'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:23 GMT
recorded_with: VCR 2.9.3
