---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:49:15 GMT
      Request-Id:
      - 150384d7-b2df-4545-90cd-057d7a2e2813
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.119044499'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/25 09:38:03 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:49:15 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-properties
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:49:16 GMT
      ETag:
      - ! '"12fb7ad0ab91b0fff7207fccd253e8ec"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:49:09 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2359'
      Request-Id:
      - 4f0e3adf-17a3-46bc-8fd9-152b59fe299f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.074901159'
      Content-Length:
      - '391'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-25T16:49:08Z","id":"c928079a-b6fc-4f04-83fc-b6629db14f84","git_url":"git@heroku.com:paasal-test-app-min-properties.git","maintenance":false,"name":"paasal-test-app-min-properties","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-25T16:49:09Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-25T16:49:09Z","web_url":"https://paasal-test-app-min-properties.herokuapp.com/"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:49:16 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:49:16 GMT
      ETag:
      - ! '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2358'
      Request-Id:
      - abb124b0-8e0b-47fa-b846-0b61a1c7cbd5
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.147738165'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:49:16 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:49:17 GMT
      ETag:
      - ! '"12fb7ad0ab91b0fff7207fccd253e8ec"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:49:09 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2357'
      Request-Id:
      - 584fde45-74c7-4e6a-a474-def0585279fa
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.055438753'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:49:17 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:49:18 GMT
      ETag:
      - ! '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2356'
      Request-Id:
      - cac07ab1-9ffb-4999-95e8-6624328e4809
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.045158641'
      Content-Length:
      - '98'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-java"},"ordinal":0}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:49:18 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..2
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:49:18 GMT
      ETag:
      - ! '"5eb4aaa8dbc07ba312b4759bd4e70931"'
      Last-Modified:
      - Wed, 25 Mar 2015 09:49:09 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2355'
      Request-Id:
      - efec06ed-dcad-4e79-9cc4-20111d5a3c01
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.062690728'
      Content-Length:
      - '326'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"app":{"id":"c928079a-b6fc-4f04-83fc-b6629db14f84","name":"paasal-test-app-min-properties"},"created_at":"2015-03-25T16:49:08Z","description":"Initial
        release","id":"b6761103-2253-40b5-b26e-4ffc183b6073","slug":null,"updated_at":"2015-03-25T16:49:08Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"c928079a-b6fc-4f04-83fc-b6629db14f84","name":"paasal-test-app-min-properties"},"created_at":"2015-03-25T16:49:09Z","description":"Enable
        Logplex","id":"8c2f5838-849f-445d-944b-61bf0b84c407","slug":null,"updated_at":"2015-03-25T16:49:09Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:49:18 GMT
recorded_with: VCR 2.9.3
