---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:03 GMT
      Request-Id:
      - 7ed902d2-f4ea-48f4-bc6c-62efade8cf7d
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.12387491'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2015/04/08
        09:21:45 -0700","name":" ","updated_at":"2015/04/08 09:41:08 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:03 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-properties
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:04 GMT
      ETag:
      - '"dca42fc752cde9ebcad2c2cc2bfb6fdc"'
      Last-Modified:
      - Wed, 08 Apr 2015 16:47:57 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2381'
      Request-Id:
      - 336c478e-a448-452c-be92-a24178c84cb6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.085031424'
      Content-Length:
      - '392'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-08T16:47:56Z","id":"6fa4386d-4c59-43b3-9c2d-22cfe53c24a1","git_url":"git@heroku.com:paasal-test-app-min-properties.git","maintenance":false,"name":"paasal-test-app-min-properties","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-08T16:47:57Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-08T16:47:57Z","web_url":"https://paasal-test-app-min-properties.herokuapp.com/"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:04 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:05 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2380'
      Request-Id:
      - 8cd4e04a-8824-4a34-a6e5-00090bebb7cf
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.091724499'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:05 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:05 GMT
      ETag:
      - '"dca42fc752cde9ebcad2c2cc2bfb6fdc"'
      Last-Modified:
      - Wed, 08 Apr 2015 16:47:57 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2379'
      Request-Id:
      - 5bc3cb9a-4616-4e6d-bdbc-798613d80f48
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.051118455'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:05 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:06 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2378'
      Request-Id:
      - 71c8f9ee-8195-49c1-88f9-00735d477799
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.049780098'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:06 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..2
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:07 GMT
      ETag:
      - '"5eb4aaa8dbc07ba312b4759bd4e70931"'
      Last-Modified:
      - Wed, 08 Apr 2015 09:47:57 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2377'
      Request-Id:
      - 61996709-278c-4783-9542-c369629834a4
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.042527528'
      Content-Length:
      - '323'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"6fa4386d-4c59-43b3-9c2d-22cfe53c24a1","name":"paasal-test-app-min-properties"},"created_at":"2015-04-08T16:47:56Z","description":"Initial
        release","id":"52413af1-c140-448e-a23e-9c158eeab765","slug":null,"updated_at":"2015-04-08T16:47:56Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"6fa4386d-4c59-43b3-9c2d-22cfe53c24a1","name":"paasal-test-app-min-properties"},"created_at":"2015-04-08T16:47:57Z","description":"Enable
        Logplex","id":"13a74839-3539-48f0-b473-5b395c39ddb7","slug":null,"updated_at":"2015-04-08T16:47:57Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2}]'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:07 GMT
recorded_with: VCR 2.9.3
