---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:50:33 GMT
      Request-Id:
      - f3d2fff5-d60c-42d1-880a-a6dbd0605772
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.12565351'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/25 09:38:03 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:50:33 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/app_never_exists_0123456789/config-vars
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:50:34 GMT
      RateLimit-Remaining:
      - '2306'
      Request-Id:
      - ea77b9b8-d7c3-48ad-97af-d7f6f6afa42f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 404 Not Found
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.031826193'
      Content-Length:
      - '92'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"resource":"app","id":"not_found","message":"Couldn''t find that
        app."}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:50:34 GMT
recorded_with: VCR 2.9.3
