---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:31 GMT
      Request-Id:
      - f5f4e414-606e-4533-9f93-68991eadaa23
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.139061943'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/19 09:37:05 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:37:31 GMT
- request:
    method: patch
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated/formation
    body:
      encoding: UTF-8
      string: '{"updates":[{"process":"web","quantity":2}]}'
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message:
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:33 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global write write-protected
      RateLimit-Remaining:
      - '1798'
      Request-Id:
      - abcd8467-a6e3-425e-98ae-1dcce1445eb8
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.051838369'
      Content-Length:
      - '165'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-03-19T16:31:18Z","id":"1a9ea996-bb3d-4c65-a248-d3f2ea4b0c5e","type":"web","quantity":2,"size":"1X","updated_at":"2015-03-19T16:37:33Z"}]'
    http_version:
  recorded_at: Thu, 19 Mar 2015 16:37:33 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message:
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:34 GMT
      ETag:
      - '"23314f7eb7a69aa52277143f7d31d646"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:37:33 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '1797'
      Request-Id:
      - eff560e1-22a1-4e97-a760-99ce2d8b4529
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.029029515'
      Content-Length:
      - '413'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":"Node.js","build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-19T16:28:10Z","id":"2b04388f-0b2a-48e1-b7d6-3301afb77c4d","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-19T16:37:05Z","repo_size":2703559,"slug_size":12380666,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-19T16:37:33Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version:
  recorded_at: Thu, 19 Mar 2015 16:37:34 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/2b04388f-0b2a-48e1-b7d6-3301afb77c4d/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message:
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:34 GMT
      ETag:
      - '"bd0159262a0ceac77fd942196aef31ce"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:37:12 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '1796'
      Request-Id:
      - 0fa54df7-0f57-42ed-8ae8-c3d8bea954dc
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.105527423'
      Content-Length:
      - '223'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"attach_url":null,"command":"node server.js","created_at":"2015-03-19T16:37:12Z","id":"eb776dae-2361-4390-8b40-823339716e2f","name":"web.1","release":{"id":"076bc6b7-103c-4c0c-bd8d-7e1400bdee89","version":7},"size":"1X","state":"up","type":"web","updated_at":"2015-03-19T16:37:12Z"}, {"attach_url":null,"command":"node server.js","created_at":"2015-03-19T16:37:12Z","id":"eb776dae-2361-4390-8b40-823339716e2f","name":"web.2","release":{"id":"076bc6b7-103c-4c0c-bd8d-7e1400bdee89","version":7},"size":"1X","state":"up","type":"web","updated_at":"2015-03-19T16:37:12Z"}]'
    http_version:
  recorded_at: Thu, 19 Mar 2015 16:37:34 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/2b04388f-0b2a-48e1-b7d6-3301afb77c4d/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message:
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:35 GMT
      ETag:
      - '"23314f7eb7a69aa52277143f7d31d646"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:37:33 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '1795'
      Request-Id:
      - 730da6e0-04c9-4719-97ca-d18006c619a8
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.027993343'
      Content-Length:
      - '165'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-03-19T16:31:18Z","id":"1a9ea996-bb3d-4c65-a248-d3f2ea4b0c5e","type":"web","quantity":2,"size":"1X","updated_at":"2015-03-19T16:37:33Z"}]'
    http_version:
  recorded_at: Thu, 19 Mar 2015 16:37:35 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/2b04388f-0b2a-48e1-b7d6-3301afb77c4d/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message:
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:36 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '1794'
      Request-Id:
      - e4f9e683-1c2d-4a04-b1a6-2cd3f9bc72bc
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.042540307'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version:
  recorded_at: Thu, 19 Mar 2015 16:37:35 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/2b04388f-0b2a-48e1-b7d6-3301afb77c4d/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message:
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:37:36 GMT
      ETag:
      - '"bd0159262a0ceac77fd942196aef31ce"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:37:12 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '1793'
      Request-Id:
      - aa2a86cd-4689-43ca-a925-75b6c8c1829e
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.093848449'
      Content-Length:
      - '223'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"attach_url":null,"command":"node server.js","created_at":"2015-03-19T16:37:12Z","id":"eb776dae-2361-4390-8b40-823339716e2f","name":"web.1","release":{"id":"076bc6b7-103c-4c0c-bd8d-7e1400bdee89","version":7},"size":"1X","state":"up","type":"web","updated_at":"2015-03-19T16:37:12Z"}, {"attach_url":null,"command":"node server.js","created_at":"2015-03-19T16:37:12Z","id":"eb776dae-2361-4390-8b40-823339716e2f","name":"web.2","release":{"id":"076bc6b7-103c-4c0c-bd8d-7e1400bdee89","version":7},"size":"1X","state":"up","type":"web","updated_at":"2015-03-19T16:37:12Z"}]'
    http_version:
  recorded_at: Thu, 19 Mar 2015 16:37:36 GMT
recorded_with: VCR 2.9.3
