---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:59:55 GMT
      Request-Id:
      - d41a31be-ca74-42d6-8a0b-b96d385aa837
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.139820867'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2015/04/08
        09:21:45 -0700","name":" ","updated_at":"2015/04/08 09:52:47 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:59:55 GMT
- request:
    method: patch
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated/formation
    body:
      encoding: UTF-8
      string: '{"updates":[{"process":"web","quantity":1}]}'
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:59:56 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global write write-protected
      RateLimit-Remaining:
      - '2208'
      Request-Id:
      - ecc11f8b-70b1-40f8-8a98-32c463f45e30
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.055849592'
      Content-Length:
      - '165'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-04-08T16:52:47Z","id":"bb6904b4-7225-424c-a3f0-c417a47dc601","type":"web","quantity":1,"size":"1X","updated_at":"2015-04-08T16:59:56Z"}]'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:59:56 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:59:57 GMT
      ETag:
      - '"3e873c1844d5e517330b66e1db6c19d2"'
      Last-Modified:
      - Wed, 08 Apr 2015 16:59:56 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2207'
      Request-Id:
      - eafc6c86-65eb-4e7f-b494-a12921bd22cb
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.0484747'
      Content-Length:
      - '411'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":"Node.js","build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-08T16:47:56Z","id":"6fa4386d-4c59-43b3-9c2d-22cfe53c24a1","git_url":"git@heroku.com:paasal-test-app-min-updated.git","maintenance":false,"name":"paasal-test-app-min-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-08T16:52:47Z","repo_size":2703817,"slug_size":12556350,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-08T16:59:56Z","web_url":"https://paasal-test-app-min-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:59:57 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:59:58 GMT
      ETag:
      - '"ff996796d6d267cd9c392cce0446fc84"'
      Last-Modified:
      - Wed, 08 Apr 2015 16:54:34 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2206'
      Request-Id:
      - 4f144e1d-0f4b-481e-93de-f5e7ac652ed8
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.084806679'
      Content-Length:
      - '224'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"attach_url":null,"command":"node server.js","created_at":"2015-04-08T16:54:34Z","id":"94c1752a-c7f6-479b-9e7f-d5b6622151a6","name":"web.1","release":{"id":"902b4fa4-b0aa-45ab-866f-33357245b86e","version":4},"size":"1X","state":"up","type":"web","updated_at":"2015-04-08T16:54:34Z"}]'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:59:58 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:59:58 GMT
      ETag:
      - '"3e873c1844d5e517330b66e1db6c19d2"'
      Last-Modified:
      - Wed, 08 Apr 2015 16:59:56 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2205'
      Request-Id:
      - 5d34f8d8-d152-49c2-a5f6-d7877febd2c6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.025068079'
      Content-Length:
      - '165'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-04-08T16:52:47Z","id":"bb6904b4-7225-424c-a3f0-c417a47dc601","type":"web","quantity":1,"size":"1X","updated_at":"2015-04-08T16:59:56Z"}]'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:59:58 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/6fa4386d-4c59-43b3-9c2d-22cfe53c24a1/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:59:59 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2204'
      Request-Id:
      - d4807bbb-7d3e-45f7-a6ee-e0284dc70dde
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.043187754'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:59:59 GMT
recorded_with: VCR 2.9.3
