---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:51 GMT
      Request-Id:
      - 299064a6-2ca3-4fca-9eeb-86acee6af9ec
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.135934732'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/19 09:27:04 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:51 GMT
- request:
    method: put
    uri: https://api.heroku.com/apps/app_never_exists_0123456789/buildpack-installations
    body:
      encoding: UTF-8
      string: '{"updates":[{"buildpack":"https://github.com/heroku/heroku-buildpack-ruby"}]}'
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:28:52 GMT
      RateLimit-Remaining:
      - '2018'
      Request-Id:
      - 4814aebc-93e7-4c16-ad2d-b04d0609c7a2
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 404 Not Found
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.025428927'
      Content-Length:
      - '92'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"resource":"app","id":"not_found","message":"Couldn''t find that app."}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:28:52 GMT
recorded_with: VCR 2.9.3
