---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:12:53 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - e7ca18fb-f9a3-4cdb-5de0-d54d96ae7ee7
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - edb9dd0d-f13d-4c67-5fdc-eb621d08287e::eebbc849-6afb-4bd2-bef7-07decda1a273
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:12:53 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Mon, 06 Apr 2015 20:12:52 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - ff62a6c1-533a-47e3-6feb-95caf943c35c, a88a2056-cf19-4951-7bd7-9314417c2240
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"1969d1db-534d-4fbc-8dbc-03ee6d83f898"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:12:53 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:12:53 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 6c1ea1a9-6ff2-4a74-530d-c49b82050997
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - d2f2071a-e0ef-46d1-76eb-0f8f761a3b3b::1868957a-eac4-4d4c-bbc5-1f0c9fee1f7e
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:12:53 GMT
recorded_with: VCR 2.9.3
