---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:53 GMT
      Request-Id:
      - d94fe5cb-ebbd-4548-9c0d-ffbc04626a2e
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.144297108'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2015/04/08
        09:21:45 -0700","name":" ","updated_at":"2015/04/08 09:41:08 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:53 GMT
- request:
    method: put
    uri: https://api.heroku.com/apps/app_never_exists_0123456789/buildpack-installations
    body:
      encoding: UTF-8
      string: '{"updates":[{"buildpack":"https://github.com/heroku/heroku-buildpack-ruby"}]}'
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 16:48:54 GMT
      RateLimit-Remaining:
      - '2351'
      Request-Id:
      - 8ef0e36f-bcf3-4118-ac59-380b1cbae5b5
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 404 Not Found
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.018918323'
      Content-Length:
      - '92'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"resource":"app","id":"not_found","message":"Couldn''t find that app."}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 16:48:54 GMT
recorded_with: VCR 2.9.3
