---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:34:58 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 8ad0cf55-e7f5-43b2-5213-bb6615cdd8e4
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 14270f8d-38ef-4027-7281-4ffe40eddfe0::45d5f700-f9bd-4dee-b613-2cb28376157a
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:42:49 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Thu, 02 Apr 2015 12:34:58 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 39e6a31d-1daf-43af-4811-3c231cd8a7e1, 73d334b4-8079-41d3-654a-52d93eafbd4b
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"e29ec8e1-d1f6-4c5b-9511-361259f677c3"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:42:50 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:34:58 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 0ba15417-3dda-4978-5e84-9221f7ed309d
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - a26a64d3-b19c-4d0a-471f-b207ecf7bce8::c054120a-9a66-4760-be43-6e396d2cd1b0
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:42:50 GMT
recorded_with: VCR 2.9.3
