---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 19 Mar 2015 16:35:23 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 68183a41-571a-4b24-4d9f-943570a0d0ec
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 03dd5aaf-87f4-4f0c-5234-71d8cde266dc::4e71ffd0-4aa1-4408-a311-e79a4a782f51
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:35:23 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Thu, 19 Mar 2015 16:35:24 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - a2987df9-a461-47de-7136-9ab116f43c5a, e6c62be2-7f78-4b4d-5040-8e52d9538e6e
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"7e018da9-d71c-48be-959b-5c05c4d538af"}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:35:24 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 19 Mar 2015 16:35:24 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 47cc8e94-2627-4d47-4623-3017b2924b84
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 1f274bb5-f7ea-4e07-7809-0ed9deb6cd75::fb7ba889-365e-4b9f-82e3-8f10604fe2f4
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:35:24 GMT
recorded_with: VCR 2.9.3
