---
http_interactions:
- request:
    method: post
    uri: https://api.cloudcontrol.com/token
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - bytes
      Access-Control-Allow-Headers:
      - X-Requested-With, Authorization, Content-Type, Content-Length, Accept
      Access-Control-Allow-Methods:
      - POST, GET, PUT, DELETE
      Access-Control-Allow-Origin:
      - "*"
      Age:
      - '0'
      Allow:
      - POST, OPTIONS
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 18:01:37 GMT
      Server:
      - gunicorn/19.2.1
      Strict-Transport-Security:
      - max-age=15768000
      Vary:
      - Accept
      Via:
      - 1.1 varnish
      x-host:
      - api.cloudcontrol.com
      x-url:
      - "/token"
      X-Varnish:
      - '1146458346'
      X-varnish-cache:
      - MISS
      Content-Length:
      - '84'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"token": "__TOKEN__", "expires": "2015-04-08T18:16:37.486432"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 18:01:37 GMT
- request:
    method: get
    uri: https://api.cloudcontrol.com/app/app_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 410
      message: 
    headers:
      Accept-Ranges:
      - bytes
      Access-Control-Allow-Headers:
      - X-Requested-With, Authorization, Content-Type, Content-Length, Accept
      Access-Control-Allow-Methods:
      - POST, GET, PUT, DELETE
      Access-Control-Allow-Origin:
      - "*"
      Age:
      - '0'
      Allow:
      - GET, POST, DELETE, HEAD, OPTIONS
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 18:01:37 GMT
      Server:
      - gunicorn/19.2.1
      Strict-Transport-Security:
      - max-age=15768000
      Vary:
      - Accept, Cookie
      Via:
      - 1.1 varnish
      x-host:
      - api.cloudcontrol.com
      x-url:
      - "/app/app_never_exists_0123456789"
      X-Varnish:
      - '1058876158'
      X-varnish-cache:
      - MISS
      Content-Length:
      - '4'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: Gone
    http_version: 
  recorded_at: Wed, 08 Apr 2015 18:01:37 GMT
recorded_with: VCR 2.9.3
