---
version: "v1"
methods:
  -
    name: "start"
  -
    name: "stop"
  -
    name: "restart"
  -
    name: "authenticate"
    arguments: 2
  -
    name: "applications"
  -
    name: "application"
    arguments: 1
  -
    name: "create_application"
    arguments: 1
  -
    name: "update_application"
    arguments: 2
  -
    name: "delete_application"
    arguments: 1
  -
    name: "env_vars"
    arguments: 1
  -
    name: "env_var"
    arguments: 2
  -
    name: "create_env_var"
    arguments: 1
  -
    name: "update_env_var"
    arguments: 2
  -
    name: "delete_env_var"
    arguments: 1
  -
    name: "domains"
    arguments: 1
  -
    name: "domain"
    arguments: 2
  -
    name: "create_domain"
    arguments: 1
  -
    name: "update_domain"
    arguments: 2
  -
    name: "delete_domain"
    arguments: 1
