---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:31 GMT
      Request-Id:
      - e9a02782-8432-46a3-afbd-5127096aa86f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.136795109'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/25 09:53:28 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:31 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:32 GMT
      ETag:
      - ! '"ff1b041bcadb33e1acc854ac0f3740f8"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:53:30 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2320'
      Request-Id:
      - a41252f5-6bd5-4fd6-bab5-b93353ade8c6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.060953135'
      Content-Length:
      - '408'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"archived_at":null,"buildpack_provided_description":"Node.js","build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-25T16:49:08Z","id":"c928079a-b6fc-4f04-83fc-b6629db14f84","git_url":"git@heroku.com:paasal-test-app-min-updated.git","maintenance":false,"name":"paasal-test-app-min-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-25T16:53:28Z","repo_size":null,"slug_size":12384674,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-25T16:53:30Z","web_url":"https://paasal-test-app-min-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:32 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:33 GMT
      ETag:
      - ! '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2319'
      Request-Id:
      - 54bfa9d7-595f-4c38-aed7-584fc705ff6e
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.11127639'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:33 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:33 GMT
      ETag:
      - ! '"ff1b041bcadb33e1acc854ac0f3740f8"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:53:30 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2318'
      Request-Id:
      - 7451653a-9d53-4dd8-b750-6737d92221ea
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.030169627'
      Content-Length:
      - '163'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"command":"node server.js","created_at":"2015-03-25T16:53:28Z","id":"76571622-bed2-45b7-809e-e7e4100bb3e7","type":"web","quantity":0,"size":"1X","updated_at":"2015-03-25T16:53:30Z"}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:33 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:34 GMT
      ETag:
      - ! '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2317'
      Request-Id:
      - 834c4b2e-e174-444a-81d0-a53ee7c10bed
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.043616542'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:34 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/c928079a-b6fc-4f04-83fc-b6629db14f84/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..4
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:34 GMT
      ETag:
      - ! '"5ba3a57111dce263b665db6a33c161db"'
      Last-Modified:
      - Wed, 25 Mar 2015 09:53:28 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2316'
      Request-Id:
      - cccffd16-0a02-48ec-9182-feb567f9789b
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.033757015'
      Content-Length:
      - '470'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"app":{"id":"c928079a-b6fc-4f04-83fc-b6629db14f84","name":"paasal-test-app-min-updated"},"created_at":"2015-03-25T16:49:08Z","description":"Initial
        release","id":"b6761103-2253-40b5-b26e-4ffc183b6073","slug":null,"updated_at":"2015-03-25T16:49:08Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"c928079a-b6fc-4f04-83fc-b6629db14f84","name":"paasal-test-app-min-updated"},"created_at":"2015-03-25T16:49:09Z","description":"Enable
        Logplex","id":"8c2f5838-849f-445d-944b-61bf0b84c407","slug":null,"updated_at":"2015-03-25T16:49:09Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2},{"app":{"id":"c928079a-b6fc-4f04-83fc-b6629db14f84","name":"paasal-test-app-min-updated"},"created_at":"2015-03-25T16:50:50Z","description":"Set
        our_test_var_key config vars","id":"814b71b9-cbd0-4088-bd82-c7a84dffbbdd","slug":null,"updated_at":"2015-03-25T16:50:50Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":3},{"app":{"id":"c928079a-b6fc-4f04-83fc-b6629db14f84","name":"paasal-test-app-min-updated"},"created_at":"2015-03-25T16:53:28Z","description":"Deploy
        ef33758","id":"01ccd2f4-b3b6-4ab7-8f94-157da8769f03","slug":{"id":"dbd94e44-e75b-43b1-941c-2f69edc67b8e"},"updated_at":"2015-03-25T16:53:28Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":4}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:34 GMT
recorded_with: VCR 2.9.3
