---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:03 GMT
      Request-Id:
      - 6e2f6e12-d6d7-45aa-acd6-bba5bdefef93
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.155515891'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/04/06 13:38:00 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:04 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:04 GMT
      ETag:
      - '"06f9e714a71e63e55f88e08ff00abe8e"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:38:02 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2140'
      Request-Id:
      - 00bb153d-57e8-4f15-ac41-c44bde0b13a0
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.108052324'
      Content-Length:
      - '410'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":"Node.js","build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-06T20:34:46Z","id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-06T20:38:00Z","repo_size":2703855,"slug_size":12565235,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-06T20:38:04Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:05 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:04 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2139'
      Request-Id:
      - 8e10d60c-7f23-4e65-99bc-2df9364dd928
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.12058668'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:06 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:05 GMT
      ETag:
      - '"5cfb3e0f315af8f6fa77ed9a327747aa"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:38:04 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2138'
      Request-Id:
      - 55042edc-3cbb-4a6d-b75b-1664d3e0852f
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.053847268'
      Content-Length:
      - '162'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-04-06T20:38:00Z","id":"11f8b3ac-ea32-4af4-8d8e-da2c7234dc05","type":"web","quantity":0,"size":"1X","updated_at":"2015-04-06T20:38:02Z"}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:06 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:06 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2137'
      Request-Id:
      - 9aeeaedf-0117-48b0-a81d-a59298f49e81
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.077418602'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:07 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/5b811f57-85dd-40bc-b95c-cb80903f88ee/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..6
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:06 GMT
      ETag:
      - '"0248173443b6c6e8455c4a73c615628a"'
      Last-Modified:
      - Mon, 06 Apr 2015 13:38:00 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2136'
      Request-Id:
      - 8f2866a8-62b9-4175-b567-6d18baa366e0
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.042110978'
      Content-Length:
      - '540'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:34:46Z","description":"Initial
        release","id":"d07fe512-f94b-46e8-948e-bec155745725","slug":null,"updated_at":"2015-04-06T20:34:46Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:34:47Z","description":"Enable
        Logplex","id":"dff6c310-5c2f-45b2-856c-ffef987ae966","slug":null,"updated_at":"2015-04-06T20:34:47Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2},{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:36:16Z","description":"Set
        our_test_var_key config vars","id":"2751f2c2-5f6d-4263-a419-c49b54909ab9","slug":null,"updated_at":"2015-04-06T20:36:16Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":3},{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:36:18Z","description":"Set
        our_test_var_key2 config vars","id":"5981beba-ff45-4ca5-954a-14ddfa8ab34e","slug":null,"updated_at":"2015-04-06T20:36:18Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":4},{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:36:30Z","description":"Set
        our_test_var_key config vars","id":"21db92f4-f21e-407f-9dcc-f650f239dfef","slug":null,"updated_at":"2015-04-06T20:36:30Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":5},{"app":{"id":"5b811f57-85dd-40bc-b95c-cb80903f88ee","name":"paasal-test-app-all-updated"},"created_at":"2015-04-06T20:38:00Z","description":"Deploy
        a1d4d89","id":"91159089-bd0e-48d5-940b-c59437f3c25a","slug":{"id":"a335a53a-804e-4cee-a58f-39c53360aab8"},"updated_at":"2015-04-06T20:38:00Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":6}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:07 GMT
recorded_with: VCR 2.9.3
