---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:35 GMT
      Request-Id:
      - 8590d71b-9b2a-409c-9617-65cd99455bf4
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.161500974'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/25 09:52:32 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:35 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:35 GMT
      ETag:
      - ! '"c7f4b639154711ac8e0f29f40a946cb2"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:52:33 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2308'
      Request-Id:
      - 9a94ffd7-7d7c-493f-a1d3-558f22d8857c
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.071577165'
      Content-Length:
      - '412'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"archived_at":null,"buildpack_provided_description":"Node.js","build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-25T16:49:03Z","id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-25T16:52:32Z","repo_size":2703602,"slug_size":12402829,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-25T16:52:35Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:36 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/0bb04d40-51d7-4907-97ed-0fc2b317371b/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:36 GMT
      ETag:
      - ! '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2307'
      Request-Id:
      - 91c2b99b-6221-40ec-94e8-a64f7346be46
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.093194221'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:36 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/0bb04d40-51d7-4907-97ed-0fc2b317371b/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:37 GMT
      ETag:
      - ! '"5f60002449a9e757da67574e2e64f9cb"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:52:35 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2306'
      Request-Id:
      - 527c05b1-419f-4581-af2a-c8eee5cb9ad1
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.029985304'
      Content-Length:
      - '164'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"command":"node server.js","created_at":"2015-03-25T16:52:32Z","id":"41ca9a8d-ba47-41f8-b973-79acc2552b09","type":"web","quantity":0,"size":"1X","updated_at":"2015-03-25T16:52:33Z"}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:37 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/0bb04d40-51d7-4907-97ed-0fc2b317371b/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:37 GMT
      ETag:
      - ! '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2305'
      Request-Id:
      - ab89f0c9-acca-41e0-a078-8c72f1b952c6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.026539675'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:37 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/0bb04d40-51d7-4907-97ed-0fc2b317371b/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..6
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:38 GMT
      ETag:
      - ! '"0248173443b6c6e8455c4a73c615628a"'
      Last-Modified:
      - Wed, 25 Mar 2015 09:52:32 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2304'
      Request-Id:
      - db2b48b2-f64a-45a5-8076-5fd81e86b22c
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.033944868'
      Content-Length:
      - '540'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"app":{"id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","name":"paasal-test-app-all-updated"},"created_at":"2015-03-25T16:49:03Z","description":"Initial
        release","id":"9f13865e-1b28-4a16-b551-d49caf056dbf","slug":null,"updated_at":"2015-03-25T16:49:03Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","name":"paasal-test-app-all-updated"},"created_at":"2015-03-25T16:49:03Z","description":"Enable
        Logplex","id":"5e12048c-b176-4cfe-8bd0-2b6a641e14bc","slug":null,"updated_at":"2015-03-25T16:49:03Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2},{"app":{"id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","name":"paasal-test-app-all-updated"},"created_at":"2015-03-25T16:50:41Z","description":"Set
        our_test_var_key config vars","id":"dcf83f93-e6fa-43f1-b676-4ff04719d8f0","slug":null,"updated_at":"2015-03-25T16:50:41Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":3},{"app":{"id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","name":"paasal-test-app-all-updated"},"created_at":"2015-03-25T16:50:44Z","description":"Set
        our_test_var_key2 config vars","id":"7bd0bf8a-219d-493f-96e5-da230a4c2862","slug":null,"updated_at":"2015-03-25T16:50:44Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":4},{"app":{"id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","name":"paasal-test-app-all-updated"},"created_at":"2015-03-25T16:50:57Z","description":"Set
        our_test_var_key config vars","id":"37440c14-871d-4007-beb2-385669fae134","slug":null,"updated_at":"2015-03-25T16:50:57Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":5},{"app":{"id":"0bb04d40-51d7-4907-97ed-0fc2b317371b","name":"paasal-test-app-all-updated"},"created_at":"2015-03-25T16:52:32Z","description":"Deploy
        04a8af1","id":"ed532a0b-91b3-4b9d-bfb9-9074a8f49a74","slug":{"id":"30c22a28-00fb-4f3b-bb1d-63e235a389a2"},"updated_at":"2015-03-25T16:52:32Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":6}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:38 GMT
recorded_with: VCR 2.9.3
