---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:38:32 GMT
      Request-Id:
      - ac0870f7-28b1-4b6c-8ccf-4166e8f0683a
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.16434067'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/04/02 06:38:29 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:38:32 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:38:32 GMT
      ETag:
      - '"57554bf2ca6314d048908e3be3cbe33e"'
      Last-Modified:
      - Thu, 02 Apr 2015 13:38:30 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2325'
      Request-Id:
      - ca492f5b-7c6d-4dae-a70e-f306a012f347
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.056377257'
      Content-Length:
      - '410'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":"Node.js","build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-02T13:34:48Z","id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-02T13:38:29Z","repo_size":2703627,"slug_size":12374023,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-02T13:38:32Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:38:32 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/dynos
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:38:33 GMT
      ETag:
      - '"ec5c5ae13434766108b9afb9a42e6364"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2324'
      Request-Id:
      - b4a95ea8-8ce8-4bbb-88d3-de21d3c199bf
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.091535453'
      Content-Length:
      - '28'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:38:33 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/formation
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:38:34 GMT
      ETag:
      - '"d80bc15d58b0aac684929eea960459df"'
      Last-Modified:
      - Thu, 02 Apr 2015 13:38:32 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2323'
      Request-Id:
      - 1e2e3351-2f7a-4807-9e76-2482d400ca3c
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.051923373'
      Content-Length:
      - '163'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-04-02T13:38:29Z","id":"54b18199-8e5d-4f46-a1df-8ab8885cb086","type":"web","quantity":0,"size":"1X","updated_at":"2015-04-02T13:38:30Z"}]'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:38:34 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/buildpack-installations
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, ordinal
      Content-Encoding:
      - ''
      Content-Range:
      - ordinal 0..0
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:38:34 GMT
      ETag:
      - '"87d7b85882f94ae872184eafce30ccd8"'
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2322'
      Request-Id:
      - e83c45aa-372a-4b56-bfa2-ff10e9ed809b
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.02407665'
      Content-Length:
      - '100'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"buildpack":{"url":"https://github.com/heroku/heroku-buildpack-nodejs"},"ordinal":0}]'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:38:35 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/d6f1e01d-e744-4d61-9efc-7f37fbbd58e7/releases
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Accept-Ranges:
      - id, version
      Content-Encoding:
      - ''
      Content-Range:
      - version 1..6
      Content-Type:
      - application/json
      Date:
      - Thu, 02 Apr 2015 13:38:35 GMT
      ETag:
      - '"0248173443b6c6e8455c4a73c615628a"'
      Last-Modified:
      - Thu, 02 Apr 2015 06:38:29 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read-protected write-protected
      RateLimit-Remaining:
      - '2321'
      Request-Id:
      - d4d72f3d-7c6b-4c96-b742-36efbacbeeb2
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.040915123'
      Content-Length:
      - '544'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:34:48Z","description":"Initial
        release","id":"d981418d-47e5-4d09-a5ce-60a6b38edde7","slug":null,"updated_at":"2015-04-02T13:34:48Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":1},{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:34:49Z","description":"Enable
        Logplex","id":"fbd21090-454e-4317-92a4-6b49bafcf6cc","slug":null,"updated_at":"2015-04-02T13:34:49Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":2},{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:36:24Z","description":"Set
        our_test_var_key config vars","id":"d72eec31-3918-43ef-8c9d-f0fa3510126a","slug":null,"updated_at":"2015-04-02T13:36:24Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":3},{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:36:27Z","description":"Set
        our_test_var_key2 config vars","id":"3aa4fcf1-3ff4-480b-bd5b-a4d8a423c8d9","slug":null,"updated_at":"2015-04-02T13:36:27Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":4},{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:36:39Z","description":"Set
        our_test_var_key config vars","id":"8e2f7608-6e27-4703-8e8c-375311f07f6c","slug":null,"updated_at":"2015-04-02T13:36:39Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":5},{"app":{"id":"d6f1e01d-e744-4d61-9efc-7f37fbbd58e7","name":"paasal-test-app-all-updated"},"created_at":"2015-04-02T13:38:29Z","description":"Deploy
        d747867","id":"0b29b606-fa4c-4ace-b035-28ef38b22202","slug":{"id":"28ae8aec-8824-4cd7-a2c5-589628c11ebf"},"updated_at":"2015-04-02T13:38:29Z","user":{"email":"__heroku:user__","id":"__heroku:id__"},"version":6}]'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 13:38:35 GMT
recorded_with: VCR 2.9.3
