---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:07 GMT
      Request-Id:
      - ec89f5bb-06b2-4a8c-96a8-ddc9058b28fe
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.12431879'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/04/06 13:38:00 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:08 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:08 GMT
      ETag:
      - '"867ce13459db53aee27f2e278b41b50d"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:36:23 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2135'
      Request-Id:
      - e29e42a9-7c11-4078-8dc5-eb3c08b34fc9
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.089877518'
      Content-Length:
      - '389'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-04-06T20:34:51Z","id":"787598df-fb3a-44aa-abb2-2326ecbbda1d","git_url":"git@heroku.com:paasal-test-app-min-updated.git","maintenance":false,"name":"paasal-test-app-min-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-04-06T20:36:23Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-04-06T20:36:23Z","web_url":"https://paasal-test-app-min-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:09 GMT
- request:
    method: get
    uri: https://api.heroku.com/account
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:08 GMT
      ETag:
      - '"800607e17b99e5f2bad7d63cdbd13190"'
      Last-Modified:
      - Mon, 06 Apr 2015 20:38:00 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global identity
      RateLimit-Remaining:
      - '2134'
      Request-Id:
      - ef4f4cfc-9dfd-4399-804f-77596598d8dc
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.034877838'
      Content-Length:
      - '243'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"beta":false,"email":"__heroku:user__","id":"__heroku:id__","last_login":"2014-11-25T08:52:59Z","name":"
        ","two_factor_authentication":false,"verified":false,"created_at":"2014-11-18T09:37:21Z","updated_at":"2015-04-06T20:38:00Z","default_organization":null}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:10 GMT
- request:
    method: patch
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated/formation
    body:
      encoding: UTF-8
      string: '{"updates":[{"process":"web","quantity":0}]}'
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Mon, 06 Apr 2015 20:38:52 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global write write-protected
      RateLimit-Remaining:
      - '2153'
      Request-Id:
      - 065517f5-892d-4cd7-bbfb-0503a43a22eb
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.055869838'
      Content-Length:
      - '163'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-04-06T20:38:50Z","id":"e3ab7b8c-c48e-4e69-9de1-bf7fa9ac3eb2","type":"web","quantity":0,"size":"1X","updated_at":"2015-04-06T20:38:52Z"}]'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:38:53 GMT
recorded_with: VCR 2.9.3
