---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:30:39 GMT
      Request-Id:
      - b5c30c7a-3dc3-4bf9-9b28-35a16bcf36ef
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.169422096'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/19 09:27:04 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:30:39 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:30:40 GMT
      ETag:
      - '"b64fc75884fa8e418120390f37b3240e"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:29:44 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '1968'
      Request-Id:
      - 8cc2f8c8-f24b-4cbc-9296-15ee1a17df64
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.058361944'
      Content-Length:
      - '389'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-19T16:28:10Z","id":"2b04388f-0b2a-48e1-b7d6-3301afb77c4d","git_url":"git@heroku.com:paasal-test-app-all-updated.git","maintenance":false,"name":"paasal-test-app-all-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-19T16:29:44Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-19T16:29:44Z","web_url":"https://paasal-test-app-all-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:30:40 GMT
- request:
    method: get
    uri: https://api.heroku.com/account
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:30:40 GMT
      ETag:
      - '"23a1c6192a5a713125d969bb499a1373"'
      Last-Modified:
      - Thu, 19 Mar 2015 16:27:04 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global identity
      RateLimit-Remaining:
      - '1967'
      Request-Id:
      - 08f59b83-2581-4544-8aa1-ef963702485e
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.020350495'
      Content-Length:
      - '243'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"beta":false,"email":"__heroku:user__","id":"__heroku:id__","last_login":"2014-11-25T08:52:59Z","name":"
        ","two_factor_authentication":false,"verified":false,"created_at":"2014-11-18T09:37:21Z","updated_at":"2015-03-19T16:27:04Z","default_organization":null}'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:30:40 GMT
- request:
    method: patch
    uri: https://api.heroku.com/apps/paasal-test-app-all-updated/formation
    body:
      encoding: UTF-8
      string: '{"updates":[{"process":"web","quantity":0}]}'
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Thu, 19 Mar 2015 16:31:19 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global write write-protected
      RateLimit-Remaining:
      - '1986'
      Request-Id:
      - 848187ad-e526-40cf-b9a0-1d3825d75dee
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.089870568'
      Content-Length:
      - '163'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"command":"node server.js","created_at":"2015-03-19T16:31:18Z","id":"1a9ea996-bb3d-4c65-a248-d3f2ea4b0c5e","type":"web","quantity":0,"size":"1X","updated_at":"2015-03-19T16:31:19Z"}]'
    http_version: 
  recorded_at: Thu, 19 Mar 2015 16:31:19 GMT
recorded_with: VCR 2.9.3
