---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:39 GMT
      Request-Id:
      - 9975bd37-9a6b-421a-b532-3f4b27dcd98d
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.133808014'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2014/11/25
        00:52:59 -0800","name":" ","updated_at":"2015/03/25 09:52:32 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:39 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:40 GMT
      ETag:
      - ! '"ae2841fa2421a7d07858df6db9659303"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:50:50 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global read read-protected write write-protected
      RateLimit-Remaining:
      - '2303'
      Request-Id:
      - 6ba4d549-09b7-4faf-8684-a1ef8d032ecd
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.093629929'
      Content-Length:
      - '391'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"archived_at":null,"buildpack_provided_description":null,"build_stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"created_at":"2015-03-25T16:49:08Z","id":"c928079a-b6fc-4f04-83fc-b6629db14f84","git_url":"git@heroku.com:paasal-test-app-min-updated.git","maintenance":false,"name":"paasal-test-app-min-updated","owner":{"email":"__heroku:user__","id":"__heroku:id__"},"region":{"id":"59accabd-516d-4f0e-83e6-6e3757701145","name":"us"},"released_at":"2015-03-25T16:50:50Z","repo_size":null,"slug_size":null,"stack":{"id":"f9f9cbd7-2970-41ef-8db5-3df7123b041f","name":"cedar-14"},"updated_at":"2015-03-25T16:50:50Z","web_url":"https://paasal-test-app-min-updated.herokuapp.com/"}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:40 GMT
- request:
    method: get
    uri: https://api.heroku.com/account
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:52:40 GMT
      ETag:
      - ! '"0e1595c6023fb71ed97109577925df7b"'
      Last-Modified:
      - Wed, 25 Mar 2015 16:52:32 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global identity
      RateLimit-Remaining:
      - '2302'
      Request-Id:
      - 201d6220-a85e-432c-b85a-0551e2ea8665
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.020166521'
      Content-Length:
      - '241'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '{"allow_tracking":true,"beta":false,"email":"__heroku:user__","id":"__heroku:id__","last_login":"2014-11-25T08:52:59Z","name":"
        ","two_factor_authentication":false,"verified":false,"created_at":"2014-11-18T09:37:21Z","updated_at":"2015-03-25T16:52:32Z","default_organization":null}'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:52:40 GMT
- request:
    method: patch
    uri: https://api.heroku.com/apps/paasal-test-app-min-updated/formation
    body:
      encoding: UTF-8
      string: ! '{"updates":[{"process":"web","quantity":0}]}'
    headers:
      User-Agent:
      - excon/0.44.4
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 25 Mar 2015 16:53:30 GMT
      Oauth-Scope:
      - global
      Oauth-Scope-Accepted:
      - global write write-protected
      RateLimit-Remaining:
      - '2321'
      Request-Id:
      - 2519e0e8-5fe4-4b28-b628-4602f12fc451
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.06828691'
      Content-Length:
      - '163'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ! '[{"command":"node server.js","created_at":"2015-03-25T16:53:28Z","id":"76571622-bed2-45b7-809e-e7e4100bb3e7","type":"web","quantity":0,"size":"1X","updated_at":"2015-03-25T16:53:30Z"}]'
    http_version: 
  recorded_at: Wed, 25 Mar 2015 16:53:30 GMT
recorded_with: VCR 2.9.3
