--- 
name: "cloudControl"
id: "cloudcontrol"
providers:
  - 
    name: "cloudControl"
    id: "cloudcontrol"
    endpoints:
      - 
        name: "cloudControl"
        id: "cloudcontrol"
        url: "api.cloudcontrol.com"
  -
    name: "exoscale Apps"
    id: "exoscale"
    endpoints:
      -
        name: "exoscale Apps"
        id: "exoscale"
        url: "api.app.exo.io"
  -
    name: "Cloud&Heat App Elevator"
    id: "cloudandheat"
    endpoints:
      -
        name: "Cloud&Heat App Elevator"
        id: "cloudandheat"
        url: "api.cnh-apps.com"
