--- 
name: "Cloud Foundry"
id: "cloud-foundry"
providers:
  - 
    name: "Pivotal"
    id: "cf-pivotal"
    endpoints:
      - 
        name: "Pivotal CF"
        id: "cf-pivotal-api"
        url: "api.run.pivotal.io"
  - 
    name: "Stackato 3.4"
    id: "cf-stackato"
    endpoints:
      - 
        name: "Local installation"
        id: "cf-stackato-local"
        url: "api.stackato-vm1.local"
        # trust endpoint, no ssl certificate verification
        trust: true
