--- 
name: "cloudControl"
id: "cloudcontrol"
providers:
  - 
    name: "cloudControl"
    id: "cloudcontrol"
    endpoints:
      - 
        name: "cloudControl"
        id: "cloudcontrol"
        url: "api.cloudcontrol.com"
