--- 
name: "Cloud Foundry"
id: "cloud-foundry"
providers:
  - 
    name: "Pivotal"
    id: "cf-pivotal"
    endpoints:
      - 
        name: "Pivotal CF"
        id: "cf-pivotal-api"
        url: "api.run.pivotal.io"
  - 
    name: "Stackato 3.4"
    id: "cf-stackato"
    endpoints:
      - 
        name: "Local installation"
        id: "cf-stackato-local"
        url: "api.stackato-vm1.local"
        # trust endpoint, no ssl certificate verification
        trust: true
  -
    name: "IBM Bluemix"
    id: "bluemix"
    endpoints:
      -
        name: "Europe - Great Britain"
        id: "bluemix-eu-gb"
        url: "api.eu-gb.bluemix.net"
      -
        name: "United States - South"
        id: "bluemix-us-south"
        url: "api.ng.bluemix.net"
