--- 
name: "Cloud Foundry v2"
id: "cloud_foundry_v2"
providers:
  -
    name: "bosh"
    id: "cf-bosh"
    endpoints:
      -
        name: "bosh local"
        id: "cf-bosh-local"
        url: "api.10.244.0.34.xip.io"
        app_domain: "10.244.0.34.xip.io"
        # trust endpoint, no ssl certificate verification
        trust: true
  - 
    name: "Pivotal"
    id: "pivotal"
    endpoints:
      - 
        name: "Pivotal Web Services"
        id: "pivotal"
        url: "api.run.pivotal.io"
        app_domain: "cfapps.io"
  - 
    name: "IBM Bluemix"
    id: "bluemix"
    endpoints:
      -
        name: "Europe - Great Britain"
        id: "bluemix-eu-gb"
        url: "api.eu-gb.bluemix.net"
        app_domain: "eu-gb.mybluemix.net"
      -
        name: "United States - South"
        id: "bluemix-us-south"
        url: "api.ng.bluemix.net"
        app_domain: "ng.mybluemix.net"
  -
    name: "Anynines"
    id: "anynines"
    endpoints:
      -
        name: "Anynines"
        id: "anynines"
        url: "api.de.a9s.eu"
        app_domain: "a9s.eu"
  -
    name: "AppFog"
    id: "appfog"
    endpoints:
      -
        name: "US East"
        id: "appfog-us-east"
        url: "api.useast.appfog.ctl.io"
        app_domain: "useast.appfog.ctl.io"
      -
        name: "US West"
        id: "appfog-us-west"
        url: "api.uswest.appfog.ctl.io"
        app_domain: "uswest.appfog.ctl.io"
