---
:cloudFoundry:
  :name: Cloud Foundry
  :providers:
    :development:
    	name: Stackato
    	url: "https://localhost:9999"
    :pivotal:
    	name: Pivotal CF
      	url: "https://vsphere.provider.com/sdk"
