--- 
name: "Heroku"
id: "heroku"
providers:
  - 
    name: "Heroku"
    id: "heroku"
    endpoints:
      - 
        name: "Heroku"
        id: "heroku"
        url: "api.heroku.com"
        app_domain: "herokuapp.com"
