--- 
name: "Openshift 2"
id: "openshift2"
providers:
  - 
    name: "Openshift Online"
    id: "openshift-online"
    endpoints:
      - 
        name: "Openshift Online"
        id: "openshift-online"
        url: "openshift.redhat.com/broker/rest"
