--- 
name: "Openshift v2"
id: "openshift_v2"
providers:
  - 
    name: "Openshift Online"
    id: "openshift-online"
    endpoints:
      - 
        name: "Openshift Online"
        id: "openshift-online"
        url: "openshift.redhat.com/broker/rest"
  -
    name: "Getup Cloud"
    id: "getup"
    endpoints:
      -
        name: "Getup Cloud"
        id: "getup"
        url: "broker.getupcloud.com/broker/rest"
