---
http_interactions:
- request:
    method: post
    uri: https://api.heroku.com/login?username=__heroku:user__&password=__heroku:password__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 17:02:10 GMT
      Request-Id:
      - 45e057b2-befa-4eb1-b9f7-d07062c6757c
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.139864053'
      Content-Length:
      - '378'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"allow_tracking":true,"api_key":"__API_KEY__","beta":null,"confirmed":true,"confirmed_at":"2014/11/18
        01:37:21 -0800","created_at":"2014/11/18 01:37:21 -0800","id":"__USER_ID__@users.heroku.com","email":"__heroku:user__","last_login":"2015/04/08
        09:21:45 -0700","name":" ","updated_at":"2015/04/08 10:01:44 -0700","verified":false,"verified_at":null}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 17:02:10 GMT
- request:
    method: get
    uri: https://api.heroku.com/apps/app_never_exists_0123456789/config-vars
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Accept:
      - application/vnd.heroku+json; version=3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Encoding:
      - ''
      Content-Type:
      - application/json
      Date:
      - Wed, 08 Apr 2015 17:02:11 GMT
      RateLimit-Remaining:
      - '2206'
      Request-Id:
      - 936b89dc-eaa3-4410-8788-7bb1c52a33b6
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 404 Not Found
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Runtime:
      - '0.015308899'
      Content-Length:
      - '92'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"resource":"app","id":"not_found","message":"Couldn''t find that app."}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 17:02:11 GMT
recorded_with: VCR 2.9.3
