---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:32:50 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 229ca97f-d44e-4a18-4fc8-5c661d544c3b
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - cb4f7a8a-c0c8-4b58-4b58-19909abaad9b::921f4fef-8cf9-49b2-9aa4-53a691c3a66c
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:42 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Thu, 02 Apr 2015 12:32:49 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - cb1c6032-e6ed-4840-42dc-e1ae54aa62a8, bec8d884-87a8-4be3-679b-68aec4c6e164
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"5103c659-c8af-4a32-92b5-0f5ed9c7ae1a"}'
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:42 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/spaces
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '1465'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:32:50 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - d5ac96d3-e521-4301-4d8f-0a01fa4f4c66
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - b5cec1c3-6c39-438f-6157-e0cbee45c9e3::ef888d1e-0a7a-46a6-bae3-c5da57532af0
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 1,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [
            {
              "metadata": {
                "guid": "d3483f4f-6706-4fe1-ad90-1bd45d50e940",
                "url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940",
                "created_at": "2015-03-19T07:21:47+00:00",
                "updated_at": null
              },
              "entity": {
                "name": "development",
                "organization_guid": "d94caddf-45be-4c92-bb2d-62d3a65cbec0",
                "space_quota_definition_guid": null,
                "organization_url": "/v2/organizations/d94caddf-45be-4c92-bb2d-62d3a65cbec0",
                "developers_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/developers",
                "managers_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/managers",
                "auditors_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/auditors",
                "apps_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/apps",
                "routes_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/routes",
                "domains_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/domains",
                "service_instances_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/service_instances",
                "app_events_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/app_events",
                "events_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/events",
                "security_groups_url": "/v2/spaces/d3483f4f-6706-4fe1-ad90-1bd45d50e940/security_groups"
              }
            }
          ]
        }
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:42 GMT
- request:
    method: post
    uri: https://api.10.244.0.34.xip.io/v2/apps
    body:
      encoding: UTF-8
      string: '{"space_guid":"d3483f4f-6706-4fe1-ad90-1bd45d50e940","name":"paasal-test-app-min-properties","buildpack":"nodejs_buildpack"}'
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 400
      message: 
    headers:
      Content-Length:
      - '130'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Thu, 02 Apr 2015 12:32:50 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 87b06739-d4b9-4961-5800-0b373e035b9e
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 94a68556-0040-41ba-6c36-7183bfd5bbd5::4e6e385d-6b70-4274-a948-81f90dab9508
    body:
      encoding: UTF-8
      string: |
        {
          "code": 100002,
          "description": "The app name is taken: paasal-test-app-min-properties",
          "error_code": "CF-AppNameTaken"
        }
    http_version: 
  recorded_at: Thu, 02 Apr 2015 12:40:42 GMT
recorded_with: VCR 2.9.3
