---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:33 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 1b0d451d-a757-4f73-744e-238082080c10
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 2dca3248-bca9-423b-4126-35040267f1e7::c1cedd0d-e961-4b75-9db7-751c6ea9562a
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:32 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Sat, 04 Apr 2015 12:51:33 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - ff0af67e-07b2-496b-5de9-909054920078, 8af0aa5a-313e-4453-5392-1d6d0904fea1
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"3dab0e31-9f27-454b-ae55-e65f7bb3d6ae"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:33 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:33 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - d6dcc563-0f59-40c0-5772-4d8e8ebd8dac
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - a8a51bf1-6bc9-4805-5e25-2f2f7e216edb::eef920bb-94bc-4de7-8c41-6760d64294df
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:33 GMT
recorded_with: VCR 2.9.3
