---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:10:39 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 8ec1d90e-b547-4b4b-6ef7-f41a477738ad
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 0d6d7944-295c-49ad-455d-1a88bd3193d1::33917296-fc06-47c1-be5c-0d4d4a06cd8a
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:39 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Mon, 06 Apr 2015 20:10:40 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - adf19497-000c-487e-7209-81dc5ff2490a, 590d727f-1edc-4345-7821-8594a8d6e0e0
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"b41736e5-89b9-4271-a01e-621bc99545da"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:40 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:10:40 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 6eab8be0-9ca5-4474-7bf0-d6e90b045d5c
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - c94e7c23-f643-40e5-7a79-7c9fa1e2e796::15a26e08-6e7e-4027-87ee-cd9d65e85086
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:40 GMT
recorded_with: VCR 2.9.3
