---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:42 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - e279b0e4-f8fa-4d10-737b-0aa85b35ac87
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 9e918826-6da2-4ebc-402f-9fdc18b4e0dd::8e549771-3757-4264-9012-39d676e06d68
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:42 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Sat, 04 Apr 2015 12:51:42 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 1304e632-16a7-4310-48c2-f5feaf9b1911, 38cfdddf-73a6-4e34-5141-231c95827a75
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"c7642949-cbf4-49ea-869e-f6f32183071e"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:42 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:43 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - cbd437e7-1bab-43a0-4710-0f3f5bc7f03f
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - fc579895-2f7e-4062-6382-4c2bf633d5c6::8130aab3-0966-4c9e-b6b6-16868da43659
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:42 GMT
recorded_with: VCR 2.9.3
