---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:48 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - a0e4b60a-4d30-4300-7b63-6ee4d923d10f
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - b570c70d-ed0a-4c16-478a-7646ec023ba0::855d00d2-4b8e-4e3c-929b-92c660522ec2
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:47 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Sat, 04 Apr 2015 12:51:47 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 3b2365c3-bb61-4ac4-7964-4eb6707d6692, 5708df40-e8f5-43e7-7033-bf5fc7f247fd
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"7ce212a3-037d-41a1-a562-7c434fd83230"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:48 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:48 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - ef8565fd-d018-4fea-70d8-60d3cc5ffea6
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 93b1397b-2bf3-4d43-48b7-43fe582ce73a::a2fbaffe-1020-4727-9ab1-60e20078296e
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:48 GMT
recorded_with: VCR 2.9.3
