---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:11:34 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 468e6ed6-646d-4655-5253-3d36f20b3750
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 580a455f-1807-49a0-5a0b-89993526a062::cb13053e-668f-49ab-bcd0-3f01c4ddd469
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:11:34 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Mon, 06 Apr 2015 20:11:34 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 4affee17-3d9e-44f5-5e4b-2b9e54b8abb0, e50a22ff-ff3d-4eab-651b-29302258dbb4
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"22101fe6-1d70-4ff2-b3d1-d9ceb00f9ea0"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:11:34 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:11:34 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - b31ca7ac-6423-4d11-5ec9-3addf5140f58
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 3daadc6a-1a1a-4d00-6018-c1b73136cb6b::78294c2f-a9be-476a-b2cc-f5f6e7984493
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:11:34 GMT
recorded_with: VCR 2.9.3
