---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:10:45 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 86936734-525b-47e7-7ed9-d7e34606977f
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 50e4e778-6111-4492-6e38-b060c69cf53f::f4a7f0d4-9353-4330-96a3-b3cab035f9f7
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:45 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Mon, 06 Apr 2015 20:10:45 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - dccfdf90-b328-41ed-6aea-79bf93b8b0eb, 96e37d99-8810-4969-4db9-6deb0fd5c096
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"217549c1-0a6b-4399-8c74-292022e39880"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:45 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:10:45 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 8418f2eb-49f5-4a15-5493-57e41c3dae5c
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - aa200d08-59a5-41a1-6c5d-dd8cfd551dc6::04190bd7-62e6-47fd-9fd5-976e345a8e54
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:45 GMT
recorded_with: VCR 2.9.3
