---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 08 Apr 2015 15:37:42 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 6d0429cd-f827-4cb8-4c30-9ed906c5c95f
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - d9af0f08-6457-45ef-63ea-501d6a276bd1::ab5cfbaa-ce04-4ccf-bce8-442782587504
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 15:37:42 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 08 Apr 2015 15:37:41 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 22a07b93-2bf4-47ee-65ef-6d0494c7464f, 7ccfb110-a67b-4140-6ee1-37033dea9ecc
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"6d909d95-53f1-4dcd-b1b7-bc530e64c56c"}'
    http_version: 
  recorded_at: Wed, 08 Apr 2015 15:37:42 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Wed, 08 Apr 2015 15:37:42 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - b145e2e3-9ae0-4da3-4f4e-51516b8b7670
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 36552e3c-f865-448d-5cc4-3656407f5be8::2cb2192b-2547-451f-a221-b07608ce395e
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Wed, 08 Apr 2015 15:37:42 GMT
recorded_with: VCR 2.9.3
