---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:54 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 2a58b929-2fa7-4377-5d4a-45bfda4cf0e4
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 0f3eaf07-d203-40c5-6f7a-2547f34223aa::a71548e5-35cb-4c5d-b8a9-02d580609cd2
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:54 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Sat, 04 Apr 2015 12:51:53 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 9df4196c-3ec6-4182-66f3-4ba43adae7b7, 6c42d0a4-4a17-4587-59c6-be5451c2ac5f
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"72898655-cd2b-4913-ada9-de9f068517b4"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:54 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:51:54 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - b81b1fc3-58c1-4a8c-7a94-d236450c5413
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - d44e9dfe-0949-42cd-4970-b4816a858d1e::7e0ca678-b1fc-45d1-831c-48dabdb3d4b6
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:51:54 GMT
recorded_with: VCR 2.9.3
