---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:10:30 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 065d559f-2c65-48f3-63c5-9169d0005198
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - fb1f378c-0a59-4737-729a-c947a71b33b5::9a3dd0c1-7af8-4d18-9017-e4cb7e4cf9bf
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:29 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Mon, 06 Apr 2015 20:10:30 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 8333b767-4b0a-447d-6416-6a0f9f16b3d1, bdeb16b6-3f78-4d89-5f02-d5ced4faebb5
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"d462d277-3031-4ecf-a963-cb2b27556820"}'
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:30 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Mon, 06 Apr 2015 20:10:30 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - c28eeb38-1d03-4e28-4b98-3cbfcf696dee
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 37f2f15e-d937-4bb3-7d9e-9d63ea4feb2a::e468cb1d-e8ee-4607-bc5d-ba6c7a8717f6
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Mon, 06 Apr 2015 20:10:30 GMT
recorded_with: VCR 2.9.3
