---
http_interactions:
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '331'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:52:45 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - f237d2f5-90fe-484e-73d5-edbcc68400b0
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 8128b3eb-ccbd-43cd-76e3-ae015d176922::017ab06d-7107-4cf6-a33f-9e3c0e1cfc48
    body:
      encoding: UTF-8
      string: '{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud
        Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","api_version":"2.18.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:52:45 GMT
- request:
    method: post
    uri: http://login.10.244.0.34.xip.io/oauth/token?grant_type=password&password=__cf-bosh-local:user__&username=__cf-bosh-local:user__
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Cache-Control:
      - no-cache, no-store, no-store
      Connection:
      - close
      Content-Length:
      - '1856'
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Sat, 04 Apr 2015 12:52:45 GMT
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Pragma:
      - no-cache, no-cache
      Server:
      - Apache-Coyote/1.1
      X-Cf-Requestid:
      - 797a8c4c-ce1d-4276-463f-fe6c7c2799fe, d1f172fc-f318-4ad2-6369-15ccfe3b477a
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"access_token":"__ACCESS_TOKEN__","token_type":"bearer","refresh_token":"__REFRESH_TOKEN__","expires_in":599,"scope":"scim.userids
        cloud_controller.write password.write openid cloud_controller.read","jti":"96cfebf1-0fc2-47d1-a67c-b8d6ac10113b"}'
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:52:45 GMT
- request:
    method: get
    uri: https://api.10.244.0.34.xip.io/v2/apps?q=name%3Aapp_never_exists_0123456789
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - excon/0.45.1
      Authorization:
      - __AUTHORIZATION__
      Basic:
      - Y2Y6
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Length:
      - '107'
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Sat, 04 Apr 2015 12:52:45 GMT
      Server:
      - nginx
      X-Cf-Requestid:
      - 1452a683-1f24-4c52-5380-1f128cac12d1
      X-Content-Type-Options:
      - nosniff
      X-Vcap-Request-Id:
      - 6aaa635b-a55e-4380-4e7b-ca1ed42b6bf5::6c1e5a3b-aa01-418b-b64b-8ffe516bd715
    body:
      encoding: UTF-8
      string: |-
        {
          "total_results": 0,
          "total_pages": 1,
          "prev_url": null,
          "next_url": null,
          "resources": [

          ]
        }
    http_version: 
  recorded_at: Sat, 04 Apr 2015 12:52:45 GMT
recorded_with: VCR 2.9.3
